config/routes.rb
Rickr::Application.routes.draw do
  root :to => "estatico#index"
  match 'login' => 'estatico#login', :as => :login
  
  match 'perfil/editar' => 'usuarios#editar_perfil', :as => :editar_perfil
  match 'perfil(/:nombre_usuario)' => 'estatico#perfil', :as => :perfil
  match 'logout' => 'estatico#logout', :as => :logout
  
  match 'fotos/usuario/:id' => 'fotos#usuario', :as => :fotos_usuario
  match 'albums/usuario/:id' => 'albums#usuario', :as => :albums_usuario
  match 'albums/fotos/:id' => 'albums#fotos', :as => :fotos_del_album
  
  match 'buscar' => 'estatico#buscar', :as => :buscar
  
  match 'autenticar_twitter' => 'estatico#autenticar_twitter', :as => :autenticar_twitter
  match 'autenticacion_twitter_exitosa' => 'estatico#autenticacion_twitter_exitosa', :as => :autenticar_twitter_exito
  match 'revocar_twitter' => 'estatico#revocar_twitter', :as => :revocar_twitter

  resources :api_authentication, only: [:create]
  
  resources :albums

  resources :fotos

  resources :usuarios do
    resources :friends
    collection do
      get 'photo_urls'
    end
  end

end

app/controllers/estatico_controller.rb
class EstaticoController < ApplicationController
  def index
    @foto_home = Foto.order("created_at DESC").first
    client = TwitterOAuth::Client.new
    @tweets = client.user_timeline(:screen_name => 'rickttr', :count => 3)
  end

  def login
    if usuario = Usuario.login(params[:usuario][:nick], params[:usuario][:password])
      session[:usuario_id] = usuario.id
      redirect_to perfil_path, :notice => "Bienvenido #{usuario.nombre}!"
    else
      redirect_to :root, :notice => "Nombre de usuario o password incorrecto!"
    end
  end
  
  def perfil
    if params[:nombre_usuario]
      if usuario = Usuario.find_by_usuario(params[:nombre_usuario])
        @usuario = usuario
      else
        redirect_to :root, :notice => "No existe un usuario asociado!"
      end
    elsif session[:usuario_id]
      @usuario = Usuario.find(session[:usuario_id])
      if @usuario.twitter_token
        client = TwitterOAuth::Client.new(
            :consumer_key => 'pL1pKkqHiHdnsjonRnDg',
            :consumer_secret => 'nCn8hV7DhEA3rK3O0K9madWXNdmODvMRLeFGhKJBM',
            :token => @usuario.twitter_token,
            :secret => @usuario.twitter_verifier
            )
        @tweets = client.user_timeline(:count => 3)
      end
    else
      redirect_to :root, :notice => "No existe un usuario asociado!"
    end
  end
  
  def logout
    reset_session
    redirect_to :root, :notice => "Has salido exitosamente de rickr"
  end
  
  def buscar
     if params[:busqueda]
       @resultados = case params[:tipo]
         when 'usuarios' then Usuario.where('nombre LIKE ? OR apellido LIKE ? OR usuario LIKE ?', "%#{params[:busqueda]}%","%#{params[:busqueda]}%","%#{params[:busqueda]}%")
         when 'albums' then Album.where('nombre LIKE ? OR descripcion LIKE ?', "%#{params[:busqueda]}%","%#{params[:busqueda]}%")
         else Foto.where('nombre LIKE ? OR descripcion LIKE ?', "%#{params[:busqueda]}%","%#{params[:busqueda]}%")
       end
       @busqueda = params[:busqueda]
       @tipo = params[:tipo]
     else
       redirect_to :root, :notice => "No has introducido un termino de busqueda!"
     end
   end
   
   def autenticar_twitter
     if session[:usuario_id]
       client = TwitterOAuth::Client.new(
           :consumer_key => 'pL1pKkqHiHdnsjonRnDg',
           :consumer_secret => 'nCn8hV7DhEA3rK3O0K9madWXNdmODvMRLeFGhKJBM'
       )
       request_token = client.request_token(:oauth_callback => 'http://rickr.dev/autenticacion_twitter_exitosa')
       session[:twitter_request_token] = request_token
       redirect_to request_token.authorize_url
     else
       redirect_to :root, notice: "Debes estar logeado para poder autenticarte con Twitter!"
     end
   end
   
   def autenticacion_twitter_exitosa
     if params[:oauth_token]
       usuario = Usuario.find(session[:usuario_id])
       client = TwitterOAuth::Client.new(
           :consumer_key => 'pL1pKkqHiHdnsjonRnDg',
           :consumer_secret => 'nCn8hV7DhEA3rK3O0K9madWXNdmODvMRLeFGhKJBM'
       )
       request_token = session[:twitter_request_token]
       access_token = client.authorize(
         request_token.token,
         request_token.secret,
         :oauth_verifier => params[:oauth_verifier]
       )
       usuario.twitter_token = access_token.token
       usuario.twitter_verifier = access_token.secret
       usuario.save
       redirect_to(:root, :notice => "Conexion con Twitter exitosa!")
     else
       redirect_to(:root, :notice => "Conexion con Twitter tuvo problemas. Por favor intenta nuevamente")
     end
   end
   
   def revocar_twitter
     usuario = Usuario.find(session[:usuario_id])
     usuario.twitter_token = nil
     usuario.twitter_verifier = nil
     usuario.save
     redirect_to :root, notice: 'Conexion con Twitter revocada!'
   end
end

app/helpers/estatico_helper.rb
module EstaticoHelper
end

app/views/estatico/_buscar_listado.html.erb
<% if @resultados.size > 0 %>
  <% @resultados.each do |resultado| %>
  <div class="busqueda_elemento">
  	<%= resultado.nombre %>, <%= link_to 'Ver', resultado %>
  </div>
  <% end %>
<% else %>
No se han encontrado coincidencias.
<% end%>

app/views/estatico/buscar.html.erb
<h1>Busqueda de "<%= @busqueda %>"</h1>
<%= form_for '', :name => 'busqueda', :url => buscar_path, :remote => true, :method => :get do |f| %>
  <%= f.text_field :busqueda, :value => 'texto de busqueda', :title => 'texto de busqueda' %>
  <%= f.submit 'Buscar' %>
<% end %>
<ul class="busqueda_seleccion">
	<li class="<%= @tipo == nil || @tipo == 'fotos' ? 'seleccionado':'' %>">
		<%= link_to 'Fotos', "buscar?busqueda=#{@busqueda}&tipo=fotos", :id => "fotos", :remote => true %>
	</li>
	<li class="<%= @tipo == 'albumes' ? 'seleccionado':'' %>">
		<%= link_to 'Albumes', "buscar?busqueda=#{@busqueda}&tipo=albums", :id => "albums", :remote => true %>
	</li>
	<li class="<%= @tipo == 'usuarios' ? 'seleccionado':'' %>">
		<%= link_to 'Usuarios', "buscar?busqueda=#{@busqueda}&tipo=usuarios", :id => "usuarios", :remote => true %>
	</li>
</ul>
<div class="clear"></div>
<div class="busqueda_resultados" id="resultados">
	<%= render 'buscar_listado' %>
</div>

app/views/estatico/buscar.js.erb
$('#resultados').html("<%= escape_javascript(render('buscar_listado')) %>");

app/views/estatico/index.html.erb
<div id="imagen_home">
  <%= link_to image_tag(@foto_home.archivo_url), @foto_home %>
</div>
<div id="texto_home">
  <div>
    <h1>Bienvenido <br />
      a <br />
      Rickr</h1>
    <div id="formulario_home">
      <%= form_for :usuario, :url => login_path, :name => 'login', :method => :post do |f| %>
        <%= f.text_field :nick, :value => 'usuario...', :title => 'usuario...' %><br />
        <%= f.password_field :password, :value => 'password...', :title => 'password...' %><br />
        <%= f.submit 'Entrar' %><%= link_to 'Registro', new_usuario_path %>
      <% end %>
    </div>
  </div>
</div>
<div id="inferior">
  <% 1.upto(3) do |indice| %>
  <div class="paso" id="paso_<%= indice %>"><%= @tweets[indice-1]['text'] %></div>
  <% end %>
</div>

app/views/estatico/perfil.html.erb
<div class="superior_interior">
  <h1><%= @usuario.nombre %></h1>
  <% if @usuario.foto_perfil %>
  <%= image_tag(@usuario.foto_perfil_url, :style => 'width: 30px') %>
  <% else %>
  <%= image_tag('/images/usuario.png') %>
  <% end %>
</div>
<div class="clear"></div>
<div class="caja">
  <h2>Fotos</h2>
  <% @usuario.fotos.limit(2).each do |foto| %>
  <%= image_tag(foto.archivo_url) %>
  <% end %>
  <div class="clear"></div>
  <%= link_to 'Ver todas las fotos del usuario', fotos_usuario_path(@usuario.id) %>
</div>
<div class="clear"></div>
<div class="caja">
  <h2>Albumes</h2>
  <% @usuario.albums.publicados.limit(2).each do |album| %>
    <p><%= album.nombre %>: <%= album.albums_fotos.length %> foto(s)</p>
  <% end %>
  <%= link_to 'Ver todos los albums del usuario', albums_usuario_path(@usuario.id) %>
</div>
<% if @usuario.twitter_token %>
<div class="clear"></div>
<div class="caja">
  <h2>Mis tweets</h2>
  <% @tweets.each do |tweet| %>
  <p class="tweet"><%= tweet['text'] %></p>
  <% end %>
</div>
<p>Puedes revocar el acceso a Twitter de Rickr <%= link_to 'haciendo clic aqui', revocar_twitter_path %></p>
<% else %>
Puedes <%= link_to 'conectarte con twitter', autenticar_twitter_path %> y tener integrado tu twitter aca, pronto mas novedades!
<% end %>