config/routes.rb
Rickr::Application.routes.draw do
  root :to => "estatico#index"
  match 'login' => 'estatico#login', :as => :login
  
  match 'perfil/editar' => 'usuarios#editar_perfil', :as => :editar_perfil
  match 'perfil(/:nombre_usuario)' => 'estatico#perfil', :as => :perfil
  match 'logout' => 'estatico#logout', :as => :logout
  
  match 'fotos/usuario/:id' => 'fotos#usuario', :as => :fotos_usuario
  match 'albums/usuario/:id' => 'albums#usuario', :as => :albums_usuario
  match 'albums/fotos/:id' => 'albums#fotos', :as => :fotos_del_album
  
  match 'buscar' => 'estatico#buscar', :as => :buscar
  
  match 'autenticar_twitter' => 'estatico#autenticar_twitter', :as => :autenticar_twitter
  match 'autenticacion_twitter_exitosa' => 'estatico#autenticacion_twitter_exitosa', :as => :autenticar_twitter_exito
  match 'revocar_twitter' => 'estatico#revocar_twitter', :as => :revocar_twitter

  resources :api_authentication, only: [:create]
  
  resources :albums

  resources :fotos

  resources :usuarios do
    resources :friends
    collection do
      get 'photo_urls'
    end
  end

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  has_many :fotos, :dependent => :destroy 
  has_many :albums, :dependent => :destroy

  validates_presence_of :nombre, :apellido, :usuario, :password
  validates_confirmation_of :password

  before_create :assign_api_key
  
  def self.login(nombreUsuario, password)
    usuario = self.find_by_usuario(nombreUsuario)
    if usuario && password == usuario.password
      usuario
    else
      false
    end
  end
  
  def foto_perfil_url
    "/uploads/#{self.foto_perfil}"
  end
  
  def self.foto_perfil_upload(params)
    archivoSubido = params[:usuario][:foto_perfil]
    if archivoSubido
      File.open(Rails.root.join('public', 'uploads', archivoSubido.original_filename), 'wb') do |file|
        file.write(archivoSubido.read)
      end
      params[:usuario][:foto_perfil] = archivoSubido.original_filename
    end
    params
  end

  def assign_api_key
    self.api_key = SecureRandom.urlsafe_base64
  end
  
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  layout 'layout_limpio'
  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json
    end
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
    @usuario = Usuario.find(params[:id])
    redirect_to :controller => 'estatico', :action => 'perfil', :nombre_usuario => @usuario.usuario
  end

  # GET /usuarios/new
  # GET /usuarios/new.json
  def new
    @usuario = Usuario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/1/edit
  def edit
    @usuario = Usuario.find(params[:id])
  end
  
  def editar_perfil
    @usuario = Usuario.find_by_id(session[:usuario_id])
    if !@usuario
      return redirect_to :root, notice: 'Debes estar logeado para poder editar tu perfil'
    end
    render 'edit'
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(Usuario.foto_perfil_upload(params)[:usuario])

    respond_to do |format|
      if @usuario.save
        session[:usuario_id] = @usuario.id
        format.html { redirect_to perfil_path, notice: 'Te has registrado exitosamente!' }
        format.json { render json: @usuario, status: :created, location: @usuario }
      else
        format.html { render action: "new" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /usuarios/1
  # PUT /usuarios/1.json
  def update
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      if @usuario.update_attributes(Usuario.foto_perfil_upload(params)[:usuario])
        format.html { redirect_to :root, notice: 'Has actualizado tus datos exitosamente!' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario = Usuario.find(params[:id])
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2>No se ha podido crear el usuario:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellido %><br />
    <%= f.text_field :apellido %>
  </div>
  <div class="field">
    <%= f.label :usuario %><br />
    <%= f.text_field :usuario %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= label_tag 'password_confirmation', 'Confirme su password' %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <% if @usuario.foto_perfil %>
    <%= image_tag(@usuario.foto_perfil_url)%>
  <% end %> 
  <div class="field">
    <%= f.label :foto_perfil %><br />
    <%= f.file_field :foto_perfil %>
  </div>
  <div class="actions">
    <%= f.submit 'Guardar' %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editando Mis Datos</h1>

<%= render 'form' %>

<%= link_to 'Volver', :root %>

app/views/usuarios/index.html.erb
<h1>Listing usuarios</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Usuario</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @usuarios.each do |usuario| %>
  <tr>
    <td><%= usuario.nombre %></td>
    <td><%= usuario.apellido %></td>
    <td><%= usuario.usuario %></td>
    <td><%= usuario.password %></td>
    <td><%= link_to 'Ver Fotos', fotos_usuario_path(usuario.id) %></td>
    <td><%= link_to 'Ver Albums', albums_usuario_path(usuario.id) %></td>
    <td><%= link_to 'Show', usuario %></td>
    <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
    <td><%= link_to 'Destroy', usuario, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h2>Registro de Usuarios</h2>
<%= render 'form' %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @usuario.nombre %>
</p>

<p>
  <b>Apellido:</b>
  <%= @usuario.apellido %>
</p>

<p>
  <b>Usuario:</b>
  <%= @usuario.usuario %>
</p>

<p>
  <b>Password:</b>
  <%= @usuario.password %>
</p>


<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>