config/routes.rb
Rickr::Application.routes.draw do
  root :to => "estatico#index"
  match 'login' => 'estatico#login', :as => :login
  
  match 'perfil/editar' => 'usuarios#editar_perfil', :as => :editar_perfil
  match 'perfil(/:nombre_usuario)' => 'estatico#perfil', :as => :perfil
  match 'logout' => 'estatico#logout', :as => :logout
  
  match 'fotos/usuario/:id' => 'fotos#usuario', :as => :fotos_usuario
  match 'albums/usuario/:id' => 'albums#usuario', :as => :albums_usuario
  match 'albums/fotos/:id' => 'albums#fotos', :as => :fotos_del_album
  
  match 'buscar' => 'estatico#buscar', :as => :buscar
  
  match 'autenticar_twitter' => 'estatico#autenticar_twitter', :as => :autenticar_twitter
  match 'autenticacion_twitter_exitosa' => 'estatico#autenticacion_twitter_exitosa', :as => :autenticar_twitter_exito
  match 'revocar_twitter' => 'estatico#revocar_twitter', :as => :revocar_twitter

  resources :api_authentication, only: [:create]
  
  resources :albums

  resources :fotos

  resources :usuarios do
    resources :friends
    collection do
      get 'photo_urls'
    end
  end

end

app/models/foto.rb
class Foto < ActiveRecord::Base
  belongs_to :usuario
  has_many :albums_fotos
  has_many :albums , :through => :albums_fotos
  accepts_nested_attributes_for :albums_fotos, :allow_destroy => true, :reject_if => :all_blank
  
  validates_presence_of :nombre, :archivo, :usuario
  validates_associated :albums_fotos, :usuario
  
  self.per_page = 2
  
  def self.foto_upload(params)
    archivoSubido = params[:foto][:archivo]
    if archivoSubido
      File.open(Rails.root.join('public', 'uploads', archivoSubido.original_filename), 'wb') do |file|
        file.write(archivoSubido.read)
      end
      params[:foto][:archivo] = archivoSubido.original_filename
    end
    params
  end
  
  def archivo_url
    return "/uploads/#{self.archivo}"
  end
end

app/controllers/fotos_controller.rb
class FotosController < ApplicationController
  
  def usuario
    @fotos = Foto.paginate :conditions => ['usuario_id = ?', params[:id]], :page => params[:page], :order => 'created_at DESC'
    if session[:usuario_id] == params[:id]
      @usuario = Usuario.find(session[:usuario_id])
    else 
      @usuario = Usuario.find(params[:id])
    end
    render :index
  end
  
  # GET /fotos
  # GET /fotos.json
  def index
    @fotos = Foto.paginate :page => params[:page], :order => 'created_at DESC'

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fotos }
    end
  end

  # GET /fotos/1
  # GET /fotos/1.json
  def show
    @foto = Foto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @foto }
    end
  end

  # GET /fotos/new
  # GET /fotos/new.json
  def new
    @foto = Foto.new
    @foto.albums_fotos.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @foto }
    end
  end

  # GET /fotos/1/edit
  def edit
    @foto = Foto.find(params[:id])
    @foto.albums_fotos.build
  end

  # POST /fotos
  # POST /fotos.json
  def create
    @foto = Foto.new(Foto.foto_upload(params)[:foto])

    respond_to do |format|
      if @foto.save
        format.html { redirect_to @foto, notice: 'Foto was successfully created.' }
        format.json { render json: @foto, status: :created, location: @foto }
      else
        format.html { render action: "new" }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fotos/1
  # PUT /fotos/1.json
  def update
    @foto = Foto.find(params[:id])

    respond_to do |format|
      if @foto.update_attributes(Foto.foto_upload(params)[:foto])
        format.html { redirect_to @foto, notice: 'Foto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fotos/1
  # DELETE /fotos/1.json
  def destroy
    @foto = Foto.find(params[:id])
    @foto.destroy

    respond_to do |format|
      format.html { redirect_to fotos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/views/fotos/_form.html.erb
<%= form_for(@foto) do |f| %>
  <% if @foto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@foto.errors.count, "error") %> prohibited this foto from being saved:</h2>

      <ul>
      <% @foto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :archivo %><br />
    <%= f.file_field :archivo %>
  </div>
  <div class="field">
    <%= f.hidden_field :usuario_id, :value => session[:usuario_id] %>
  </div>
  <div class="field">
    <%= label_tag 'Albumes Vinculados' %><br />
    <%= f.fields_for :albums_fotos do |albumFoto| %>
      <%= albumFoto.label :album_id %><br />
      <%= albumFoto.collection_select(:album_id, Album.all, :id, :nombre, :include_blank => true) %>
      <% if albumFoto.object.album_id  %>
      <%= albumFoto.label '_destroy', 'Remover' %><%= albumFoto.check_box '_destroy' %><br />
      <% end %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fotos/edit.html.erb
<h1>Editing foto</h1>

<%= render 'form' %>

<%= link_to 'Show', @foto %> |
<%= link_to 'Back', fotos_path %>

app/views/fotos/index.html.erb
<% if @usuario %>
  <h1>Fotos de <%= @usuario.nombre %> <%= @usuario.apellido %></h1>
<% end %>
<div class="caja">
  <% @fotos.each do |foto| %>
  <div id="<%= "foto_#{foto.id}" %>" class="caja_elemento">
    <%= image_tag(foto.archivo_url) %>
    <div class="foto_informacion">
      <h4><%= foto.nombre %></h4>
      <p class="descripcion"><%= foto.descripcion %></p>
      <%= link_to 'Ver Foto', foto %>
      <% if @usuario && @usuario.id == session[:usuario_id] %>
        <%= link_to 'Editar', edit_foto_path(foto) %>
      <% end %>
    </div>
  </div>
  <% end %>
  <div class="clear" style="height: 10px"></div>
  <%= will_paginate(@fotos) %>
</div>
<% if @usuario && @usuario.id == session[:usuario_id] %>
  <%= link_to 'Nueva Foto', new_foto_path %>
<% end %>

app/views/fotos/new.html.erb
<h1>New foto</h1>

<%= render 'form' %>

<%= link_to 'Back', fotos_path %>

app/views/fotos/show.html.erb
<div class="foto_completa">
  <%= image_tag(@foto.archivo_url) %>
</div>
<h2 class="foto_titulo"><%= @foto.nombre %></h2>
<p class="descripcion foto_completa"><%= @foto.descripcion %></p>
<div class="clear"></div>
<div class="informacion_adicional">
  <% if(@foto.albums) %>
    <p class="foto_albums">Albums a los que pertenece esta foto: 
    <% @foto.albums.publicados.each do |album| %>	
      <%= link_to album.nombre, album %>
    <% end %>
    </p>
  <% end %>

  <% if @foto.usuario_id == session[:usuario_id] %>
    <%= link_to 'Editar', edit_foto_path(@foto) %> |
  <% end %>
  <%= link_to 'Volver', 'javascript: history.go(-1)' %>
</div>