config/routes.rb
Rickr::Application.routes.draw do
  root :to => "estatico#index"
  match 'login' => 'estatico#login', :as => :login
  
  match 'perfil/editar' => 'usuarios#editar_perfil', :as => :editar_perfil
  match 'perfil(/:nombre_usuario)' => 'estatico#perfil', :as => :perfil
  match 'logout' => 'estatico#logout', :as => :logout
  
  match 'fotos/usuario/:id' => 'fotos#usuario', :as => :fotos_usuario
  match 'albums/usuario/:id' => 'albums#usuario', :as => :albums_usuario
  match 'albums/fotos/:id' => 'albums#fotos', :as => :fotos_del_album
  
  match 'buscar' => 'estatico#buscar', :as => :buscar
  
  match 'autenticar_twitter' => 'estatico#autenticar_twitter', :as => :autenticar_twitter
  match 'autenticacion_twitter_exitosa' => 'estatico#autenticacion_twitter_exitosa', :as => :autenticar_twitter_exito
  match 'revocar_twitter' => 'estatico#revocar_twitter', :as => :revocar_twitter

  resources :api_authentication, only: [:create]
  
  resources :albums

  resources :fotos

  resources :usuarios do
    resources :friends
    collection do
      get 'photo_urls'
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bienvenido a Rickr</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrapper">
      <div id="superior">
        <div id="busqueda">
          <%= form_for '', :name => 'busqueda', :url => buscar_path, :method => :get do |f| %>
            <%= f.text_field :busqueda, :value => 'texto de busqueda', :title => 'texto de busqueda' %>
            <%= f.submit 'Buscar' %>
          <% end %>
        </div>
        <div id="caja_usuario">
          <div class="membrete">
            <p class="nombre">
            <% if(session[:usuario_id]) %>
            <% usuario = Usuario.find(session[:usuario_id]) %>
               <%= "#{usuario.nombre} #{usuario.apellido} (#{usuario.usuario})"%>
              <% if usuario.foto_perfil %>
                <%= image_tag(usuario.foto_perfil_url, :style => 'width: 30px') %>
              <% else %>
                <%= image_tag('/images/usuario.png') %>
              <% end %>
            <% end %>
            </p>
          </div>
          <div>
            <% if(session[:usuario_id]) %>
              <h3><%= link_to 'Ver Perfil', perfil_path %>, <%= link_to 'Editar perfil', editar_perfil_path %> o <%= link_to 'Salir', logout_path %></h3>
            <% else %>
              <h3><%= link_to 'Entra o Registrate!', :root %></h3>
            <% end %>
          </div>
        </div>
      </div>
      <div id="cuerpo">
        <% if flash[:notice] %>
        <p id="notice"><%= flash[:notice] %></p> 
        <% end %>
        <%= yield %>
      </div>
      <div id="pie">
        rickr 2012
      </div>
  </div>
</body>
</html>

app/views/layouts/layout_limpio.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bienvenido a Rickr</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if flash[:notice] %>
  <p id="notice"><%= flash[:notice] %></p> 
  <% end %>
  <div id="superior">
  </div>
  <div id="cuerpo">
    <%= yield %>
  </div>
  <div id="pie">
    rickr 2012
  </div>
</body>
</html>